package com.musicflow.app.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room [Entity] representing a user-favorited track.
 *
 * Stores only the song ID and timestamp — track metadata
 * is fetched from the [TrackEntity] table via a JOIN or
 * separate query.
 *
 * SQL schema (auto-generated by Room):
 * ```sql
 * CREATE TABLE IF NOT EXISTS favorites (
 *     song_id       TEXT    PRIMARY KEY NOT NULL,
 *     favorited_at  INTEGER NOT NULL
 * )
 * ```
 */
@Entity(tableName = "favorites")
data class FavoriteEntity(

    /** YouTube video ID — primary key, references the track. */
    @PrimaryKey
    @ColumnInfo(name = "song_id")
    val songId: String,

    /** Epoch millis when the user favorited this track. */
    @ColumnInfo(name = "favorited_at")
    val favoritedAt: Long = System.currentTimeMillis(),
)
