package com.musicflow.app.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room [Entity] representing a saved search query.
 *
 * Used to show recent searches in the search screen.
 * The query string itself is the primary key for deduplication.
 *
 * SQL schema (auto-generated by Room):
 * ```sql
 * CREATE TABLE IF NOT EXISTS search_history (
 *     query      TEXT    PRIMARY KEY NOT NULL,
 *     timestamp  INTEGER NOT NULL
 * )
 * ```
 */
@Entity(tableName = "search_history")
data class SearchHistoryEntity(

    /** The search query text — primary key for deduplication. */
    @PrimaryKey
    @ColumnInfo(name = "query")
    val query: String,

    /** Epoch millis when this query was last searched. */
    @ColumnInfo(name = "timestamp")
    val timestamp: Long = System.currentTimeMillis(),
)
