package com.musicflow.app.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room [Entity] representing a cached track in the local database.
 *
 * Design constraints:
 * - Only primitive types and strings — no `ByteArray`, no `Parcel`.
 * - Schema is version-safe: column additions are non-breaking, removals
 *   require a migration or destructive fallback.
 * - The primary key is the YouTube video ID (`songId`), which is stable
 *   across API versions.
 *
 * SQL schema (auto-generated by Room):
 * ```sql
 * CREATE TABLE IF NOT EXISTS tracks (
 *     song_id       TEXT    PRIMARY KEY NOT NULL,
 *     title         TEXT    NOT NULL DEFAULT '',
 *     artist        TEXT    NOT NULL DEFAULT '',
 *     artwork_url   TEXT    NOT NULL DEFAULT '',
 *     duration_ms   INTEGER NOT NULL DEFAULT 0
 * )
 * ```
 *
 * Indexes:
 * - Primary key index on `song_id` (implicit).
 * - No additional indexes needed for the current query surface.
 */
@Entity(tableName = "tracks")
data class TrackEntity(

    /**
     * YouTube video ID — stable, unique identifier.
     * Used as the primary key for cache lookups and deduplication.
     */
    @PrimaryKey
    @ColumnInfo(name = "song_id")
    val songId: String,

    /** Track title. Defaults to empty string if unavailable. */
    @ColumnInfo(name = "title")
    val title: String = "",

    /** Artist name. Defaults to empty string if unavailable. */
    @ColumnInfo(name = "artist")
    val artist: String = "",

    /** HTTPS URL to the track's artwork image. */
    @ColumnInfo(name = "artwork_url")
    val artworkUrl: String = "",

    /** Track duration in milliseconds. Defaults to 0 if unknown. */
    @ColumnInfo(name = "duration_ms")
    val durationMs: Long = 0L,
)
